### ISSUE TITLE
[rocm-opencl-runtime] No devices found

### ISSUE THREAD

**Issue by tpkessler** [rocm-arch/rocm-arch#710]
After the update of the packages to 5.1.0, OpenCL (and HIP) do not work anymore. `clinfo` shows zero devices on my machine:
```
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (3423.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback
  Platform Extensions function suffix             AMD
  Platform Host timer resolution                  1ns

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform
```

Same holds for HIP. I can compile programs but they won't run as no HIP platform is found. `rocminfo` works, so I think the issue is related to ROCclr.

**Comment by tpkessler** [comment]
I won't update the packages on the AUR until this is fixed.

**Comment by wsippel** [comment]
It's the same problem as #705 

`❯ AMD_LOG_LEVEL=7 clinfo 
:3:rocdevice.cpp            :414 : 21475687266 us: 76099: [tid:0x7f59a6aa6740] Initializing HSA stack.
:3:comgrctx.cpp             :33  : 21475706150 us: 76099: [tid:0x7f59a6aa6740] Loading COMGR library.
:1:comgrctx.cpp             :39  : 21475706258 us: 76099: [tid:0x7f59a6aa6740] Failed to load COMGR library.
:1:rocdevice.cpp            :627 : 21475706263 us: 76099: [tid:0x7f59a6aa6740] Code object manager initialization failed for HSA device gfx1010 (PCI ID 731f)
:1:rocdevice.cpp            :478 : 21475706265 us: 76099: [tid:0x7f59a6aa6740] Error creating new instance of Device.
`
`❯ LD_LIBRARY_PATH=/opt/rocm/llvm/lib AMD_LOG_LEVEL=4 clinfo
:3:rocdevice.cpp            :414 : 21536651861 us: 76255: [tid:0x7fe6219db740] Initializing HSA stack.
:3:comgrctx.cpp             :33  : 21536674418 us: 76255: [tid:0x7fe6219db740] Loading COMGR library.
:3:rocdevice.cpp            :203 : 21536679816 us: 76255: [tid:0x7fe6219db740] Numa selects cpu agent[0]=0x55f098e48dc0(fine=0x55f098d51150,coarse=0x55f098e49590) for gpu agent=0x55f098e49af0
:3:rocdevice.cpp            :1602: 21536680170 us: 76255: [tid:0x7fe6219db740] HMM support: 1, xnack: 0, direct host access: 40

:4:rocdevice.cpp            :1899: 21536680385 us: 76255: [tid:0x7fe6219db740] Allocate hsa host memory 0x7fe60c200000, size 0x101000
:4:rocdevice.cpp            :1899: 21536680652 us: 76255: [tid:0x7fe6219db740] Allocate hsa host memory 0x7fe5f4600000, size 0x101000
:4:runtime.cpp              :82  : 21536680823 us: 76255: [tid:0x7fe6219db740] init
`

**Comment by tpkessler** [comment]
Great analysis! Thank you very much @wsippel. I reverted some changes previously made to `rocm-llvm`. Now everything works again.

**Comment by tpkessler** [comment]
Fixed with [6287da5](https://github.com/rocm-arch/rocm-arch/commit/6287da54667b77d0d32a8354ad58b71292e5ba12)

**Comment by acxz** [comment]
https://github.com/rocm-arch/rocm-arch/commit/6287da54667b77d0d32a8354ad58b71292e5ba12#diff-e646aeb4706b9e8609ef038e2da8918548ddff41168ec82bfa93a8e79fefea42L38

This line shoud still exist for lto compilation of dependent packages.

**Comment by tpkessler** [comment]
Thanks, I'll add them.

**Comment by acxz** [comment]
Just that one line is needed nothing else

**Comment by tpkessler** [comment]
Yes. I thought I also have to add the lines to the package() function.

**Comment by tpkessler** [comment]
9d0d918d71638c035da0a8b0980e5c459e7d1e60 brings back LTO support.

**Comment by acxz** [comment]
Again I believe this is not needed:

https://github.com/rocm-arch/rocm-arch/commit/9d0d918d71638c035da0a8b0980e5c459e7d1e60#diff-e646aeb4706b9e8609ef038e2da8918548ddff41168ec82bfa93a8e79fefea42R45-R48

Just 
```
-DLLVM_BINUTILS_INCDIR=/usr/include
```

Can you remove those lines?

**Comment by tpkessler** [comment]
From what I understand, the sym link is important for LTO to work, see the PKGBUILD for `llvm-libs`, https://github.com/archlinux/svntogit-packages/blob/acf72d8d746975f750f3f69324148b042afc261e/trunk/PKGBUILD#L124

**Comment by acxz** [comment]
I see, okay!
